export const planos = [
    { nome: 'Controle 8GB', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Plano pós', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Fámilia II', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Fámilia V', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Fámilia Alto valor', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Controle 10GB', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Plano pré', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Fámilia III', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Fámilia VI', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Fámilia Premium', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Controle 15GB', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Plano empresarial', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Fámilia IV', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Fámilia VII', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
    { nome: 'Fámilia Ultra', valor: 'R$XX,XX', caracteristicas: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident exercitationem vel in nam doloremque neque!' },
];